# Docker Compose for SPINTRONIC Quantum Framework - Phase 5-7
# Apache License 2.0 - Copyright (c) 2025 Aetheron Research

version: '3.8'

services:
  # CPU-only version (default)
  pseudomode-cpu:
    build:
      context: .
      dockerfile: Dockerfile.phase5-7
      target: runtime
    image: spintronic-quantum:phase5-7-cpu
    container_name: pseudomode-framework-cpu
    hostname: pseudomode-cpu
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 16G
        reservations:
          cpus: '4'
          memory: 8G
    
    # Environment variables
    environment:
      - OMP_NUM_THREADS=8
      - OMP_PROC_BIND=spread
      - OMP_PLACES=threads
    
    # Volumes for data persistence
    volumes:
      - ./data:/workspace/data
      - ./results:/workspace/results
      - ./custom_materials:/workspace/custom_materials
    
    # Working directory
    working_dir: /workspace
    
    # Keep container running
    stdin_open: true
    tty: true
    
    # Command
    command: bash
    
    # Health check
    healthcheck:
      test: ["CMD", "pseudomode_cli", "--help"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  # GPU-enabled version (requires NVIDIA Docker runtime)
  pseudomode-gpu:
    build:
      context: .
      dockerfile: Dockerfile.gpu
      target: runtime
    image: spintronic-quantum:phase5-7-gpu
    container_name: pseudomode-framework-gpu
    hostname: pseudomode-gpu
    
    # GPU runtime
    runtime: nvidia
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '16'
          memory: 32G
        reservations:
          cpus: '8'
          memory: 16G
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu, compute, utility]
    
    # Environment variables
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - OMP_NUM_THREADS=16
      - CUDA_VISIBLE_DEVICES=0
    
    # Volumes
    volumes:
      - ./data:/workspace/data
      - ./results:/workspace/results
      - ./custom_materials:/workspace/custom_materials
    
    # Working directory
    working_dir: /workspace
    
    # Keep container running
    stdin_open: true
    tty: true
    
    # Command
    command: bash
    
    # Health check
    healthcheck:
      test: ["CMD", "pseudomode_cli", "--help"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    
    # Only start if GPU is available
    profiles:
      - gpu

  # Jupyter notebook service
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.phase5-7
      target: runtime
    image: spintronic-quantum:phase5-7-jupyter
    container_name: pseudomode-jupyter
    hostname: jupyter
    
    # Port mapping
    ports:
      - "8888:8888"
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
    
    # Environment
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - OMP_NUM_THREADS=4
    
    # Volumes
    volumes:
      - ./notebooks:/workspace/notebooks
      - ./data:/workspace/data
      - ./results:/workspace/results
    
    # Working directory
    working_dir: /workspace/notebooks
    
    # Command to start Jupyter
    command: >
      bash -c "
      pip3 install jupyter jupyterlab &&
      jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root
      "
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    # Only start when explicitly requested
    profiles:
      - jupyter

# Networks
networks:
  default:
    name: spintronic-network
    driver: bridge

# Volumes
volumes:
  data:
    name: spintronic-data
  results:
    name: spintronic-results
  notebooks:
    name: spintronic-notebooks
  custom_materials:
    name: spintronic-materials
