apiVersion: apps/v1
kind: Deployment
metadata:
  name: pseudomode-gpu
  labels:
    app: pseudomode-framework
    variant: gpu
    version: v1.0.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pseudomode-framework
      variant: gpu
  template:
    metadata:
      labels:
        app: pseudomode-framework
        variant: gpu
        version: v1.0.0
    spec:
      containers:
      - name: pseudomode-gpu
        image: pseudomode-framework:gpu-latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: USE_GPU
          value: "true"
        - name: GPU_DEVICE_ID
          value: "0"
        - name: MAX_PSEUDOMODES
          value: "10"
        - name: LOG_LEVEL
          value: "INFO"
        # The 'CUDA_VISIBLE_DEVICES' environment variable should be removed.
        # The NVIDIA device plugin will automatically set 'NVIDIA_VISIBLE_DEVICES'.
        resources:
          requests:
            memory: "8Gi"
            cpu: "2000m"
            nvidia.com/gpu: 1
          limits:
            memory: "32Gi"
            cpu: "8000m"
            nvidia.com/gpu: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: config
          mountPath: /etc/pseudomode
          readOnly: true
        - name: gpu-cache
          mountPath: /var/cache/pseudomode
        - name: shm
          mountPath: /dev/shm
      volumes:
      - name: config
        configMap:
          name: pseudomode-gpu-config
      - name: gpu-cache
        emptyDir:
          sizeLimit: 50Gi
      - name: shm
        emptyDir:
          medium: Memory
          sizeLimit: 16Gi
      nodeSelector:
        accelerator: nvidia-gpu
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: pseudomode-gpu-service
  labels:
    app: pseudomode-framework
    variant: gpu
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: pseudomode-framework
    variant: gpu
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pseudomode-gpu-config
data:
  config.json: |
    {
      "max_pseudomodes": 10,
      "adaptive_n_max": 8,
      "time_step_ps": 0.005,
      "convergence_tol": 1e-10,
      "use_gpu": true,
      "gpu_device_id": 0,
      "cuda_block_size": 256,
      "materials": [
        "graphene",
        "MoS2",
        "WS2",
        "hBN",
        "WSe2",
        "MoSe2"
      ]
    }
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pseudomode-gpu-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pseudomode-gpu
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
