apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pseudomode-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pseudomode-results-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: fast-ssd
  resources:
    requests:
      storage: 500Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: pseudomode-batch-simulation
spec:
  parallelism: 4
  completions: 4
  template:
    metadata:
      labels:
        app: pseudomode-batch
    spec:
      containers:
      - name: simulation
        image: pseudomode-framework:latest
        command: ["python"]
        args:
          - "/app/batch_simulate.py"
          - "--materials"
          - "graphene,MoS2,WS2,hBN"
          - "--output"
          - "/results"
        env:
        - name: MAX_PSEUDOMODES
          value: "6"
        - name: USE_GPU
          value: "false"
        resources:
          requests:
            memory: "4Gi"
            cpu: "2000m"
          limits:
            memory: "16Gi"
            cpu: "8000m"
        volumeMounts:
        - name: data
          mountPath: /data
        - name: results
          mountPath: /results
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: pseudomode-data-pvc
      - name: results
        persistentVolumeClaim:
          claimName: pseudomode-results-pvc
      restartPolicy: OnFailure
  backoffLimit: 3
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: pseudomode-nightly-benchmark
spec:
  schedule: "0 2 * * *"  # Run at 2 AM daily
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: benchmark
            image: pseudomode-framework:latest
            command: ["./benchmark_suite.sh"]
            env:
            - name: BENCHMARK_OUTPUT
              value: "/results/benchmarks"
            resources:
              requests:
                memory: "8Gi"
                cpu: "4000m"
              limits:
                memory: "32Gi"
                cpu: "16000m"
            volumeMounts:
            - name: results
              mountPath: /results
          volumes:
          - name: results
            persistentVolumeClaim:
              claimName: pseudomode-results-pvc
          restartPolicy: OnFailure
