# .github/actions/install-eigen3/action.yml
runs:
  using: 'composite'
  steps:
    - name: Cache Eigen3 installation
      id: cache-eigen
      uses: actions/cache@v3
      with:
        path: ${{ inputs.install-prefix }}
        key: ${{ runner.os }}-eigen-${{ inputs.version }}

    - name: Install Eigen3 if not cached
      if: steps.cache-eigen.outputs.cache-hit != 'true'
      shell: bash
      run: |
        # ... same build script as before ...
        VERSION="${{ inputs.version }}"
        PREFIX="${{ inputs.install-prefix }}"
        wget ...
        make install
