       - name: Install Eigen3
+  id: eigen
   uses: ./.github/actions/install-eigen3
+  with:
+    install-prefix: ${{ runner.temp }}/eigen3_install
 
 - name: Configure CMake
   env:
     CC: ${{ env.CC }}
     CXX: ${{ env.CXX }}
+    EIGEN_PREFIX: ${{ runner.temp }}/eigen3_install
   run: |
     cmake -B build \
       -DCMAKE_C_COMPILER="${CC}" \
       -DCMAKE_CXX_COMPILER="${CXX}" \
       -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
       -DUSE_OPENMP=ON \
       -DUSE_CUDA=OFF \
       -DBUILD_PYTHON_BINDINGS=ON \
       -DBUILD_TESTS=ON \
-      -DEigen3_DIR=$HOME/eigen3_install/share/eigen3/cmake
+      -DEigen3_DIR="${EIGEN_PREFIX}/share/eigen3/cmake"
